### PR TITLE
Permissions refactor

### PR DESCRIPTION
**Pull request by szerintedmi**
@phraktle , would you please have a look if the use of restricted makes more sense this way? I know it's not exactly as you explained but I couldn't come up a better way :)

@BYossarian : I'm tampering with your code , hope it's all fine :)

### CODE REVIEW

**Comment by szerintedmi** [comment]
Deploy preview for *augmint* processing.

Built with commit 2dcb6794724450969e512f99d4ba1fc30b8561fc

https://app.netlify.com/sites/augmint/deploys/5a7444d97b6ee84f5c711095

**Comment by szerintedmi** [comment]
as for more direct restrictions: thanks, now I get what you meant.  That was @BYossarian 's point too for the Lock contract. In general I agree but I can't see that working for all cases:

**1. MonetaryBoard**
Until we have a MonetaryBoard contract (with multisig) we want multiple accounts to be able to sign. Ie. during the pilot we can't rely on a single signer for an urgent action. Sharing a private key could be a solution but it would diminish accountability

**2. LoanManagerContracts**
We need to handle multiple LoanManagers (whitelist): 
a) for deploying new versions (while the old one can live simultaneously until the loans mature in there). 
b) More importantly when we will have different loans with different collaterals we will have multiple LoanManagers functioning.

**3. NoFeeContracts**
We have multiple contracts which must be able to transfer without fee (Loan, Lock and Exchange) so a whitelist is required. We could use hardcoded variables as you suggest + a `require(msg.sender == LoanManager || msg.sender == Lock || msg.sender == exchange`  but that couldn't work for multiple loan managers  (see 2.)

**4. ExchangeContracts and LockContracts**
In these cases we don't have a hard requirement for multiple contracts being live.
 but it makes it possible to introduce a new contract without the need of doing a full AugmintToken migration (which would be some hassle and gas cost for each user)


My thinking is that if we are using restrict for 1&2&3 anyway then using that for 4 as well shouldn't introduce an umanageble extra complexity  / security risk and in return :
1. we don't need to add extra variables and constructor params to each contract
1. we have the flexibility to deploy new versions without adding a setter (restricted again) for each param
1. we can have multiple versions in parallel
1. restrictions handled the same way for all contracts

What you think?

**Comment by phraktle** [comment]
My main concern with the earlier fine-grained approach was addressed by your change, as seen in `5_deploy_TokenAce.js`:  `await tokenAce.grantMultiplePermissions(accounts[0], ["MonetaryBoard"]);` as opposed to the prior list.

I would still find an explicit `await tokenAce.setMonetaryBoard(accounts[0]);` call better and type-safe. In fact, this should be assigned in the constructor (since there must always be a monetary board). 

You could do the same with roles with multiple parties: have an explicit `addLoanManager(account)`, `removeLoanManager(account)` and simply maintain them in a `mapping(address => bool)`. The methods to maintain and check this mapping are trivial (one-liner, or two if you wanted to log the event), so I don't see a need for abstractions for the sake of code reuse.

To your first point: arguably, it would be a reduction, not an _e txtra_ :) If you drop the `Restricted` abstraction, you would see a reduction in storage space as well as gas usage: just a simple `monetaryBoard` property (or a straight `mapping` in case of `loanManagers`) vs multiple lookups in nested mappings and hashing strings.

**Comment by szerintedmi** [comment]
makes sense, thanks.
I will merge this version and add a card to the backlog to refactor as you suggested. We can prioritise later. Unless you think it's a must for the pilot

**Pull request merged**
